version: '3.8'

services:
  judgeserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: judgeserver-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./generated_csv:/app/generated_csv
    networks:
      - shared-net
    
networks:
  shared-net:
    external: true
